# Generated by Django 5.1.5 on 2025-01-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_municipality_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='municipality',
            new_name='district',
        ),
    ]
